name: MinecraftTutorial
version: '1.1-SNAPSHOT'
main: com.ghostworld.tutorial.minecraftTutorial.MinecraftTutorial
api-version: '1.21'

commands:
  giveItem:
    description: 전설의 아이탬 을 지급합니다
    usage: /giveItem